---
title: "Joshua Quan, FY17"
output:
  pdf_document: default
  html_notebook: default
  word_document: default
---

```{r, echo= FALSE, quietly = TRUE, message = FALSE, warning = FALSE}

library(tidyverse)
library(googlesheets)
library(ggthemes)
library(gridExtra)
library(tidytext)
library(knitr)

#read in instruction stats sheet
gs_auth()


raw <- gs_url("https://docs.google.com/spreadsheets/d/1yg5lNLXUm7Upiz76a8QgyASyWJrUdRxcm9R_JwmyGA0/")

raw <- raw %>%
  gs_read(ws = "Form Responses 1")

#renames variables for easier typing

raw <- rename(raw, timestamp = `Timestamp`,
              lastname = `Your Last Name`,
              type = `Type of interaction`,
              date = `Date`,
              course = `Course Information`,
              faculty = `Faculty Name`,
              patron = `Patron Type`,
              attendees = `Number of Attendees*`,
              location = `Location`,
              delivery = `Delivery Mode`,
              time = `Time Spent`,
              notes = `Notes (can include learning goals, location of instructional materials, co-presenters etc.)`,
              copresenters = `Copresenters`)

#convert date from character
raw$date <- as.Date(raw$date, "%m/%d/%Y")

#split date into month, year variables
raw <- raw %>% separate(date, into = c("year","month", "day"),  sep = "\\-", remove = FALSE) 
  
raw$month <- as.numeric(raw$month)


raw <- mutate(raw, semester = ifelse(month %in% 01:05, "Spring",
                                     ifelse(month %in% 06:08, "Summer",
                                            ifelse(month %in% 09:12, "Fall", "NA")))) 

raw$semester <- as.factor(raw$semester)

# to look at individuals
raw1 <- filter(raw, lastname == "Quan")

ggplot(raw1, aes(date)) +
  geom_histogram(binwidth = 10, stat = "bin", alpha = .2) +
  geom_density(stat = "bin", binwidth = 10)+
  theme_tufte(base_size = 11, base_family = "serif", ticks = TRUE) +
  ggtitle("Interactions over time") 

raw1 %>% count(type) %>% kable()


```


```{r, echo = FALSE}
raw1 %>% count(delivery) %>% kable()

```
```{r, echo = FALSE}
raw1 %>% count(time) %>% kable()

```

```{r, echo = FALSE}
raw1 %>% count(location) %>% kable()

```

```{r, echo= FALSE}

raw2 <- raw1 %>% separate(course, into = c("dept","course2", "course3"),  sep = " ", extra = "drop")

#create new data.frame with just department and count
raw3 <- count(raw2, dept, semester) %>% filter(!is.na(dept))
raw3 <- arrange(raw3,desc(n))

#plot of most worked with departments
ggplot(data = raw3, aes(reorder(dept, n), n, fill = semester)) + geom_bar(stat = "identity") + coord_flip() +
  theme_tufte(base_size = 11, base_family = "serif", ticks = FALSE) +   scale_fill_ptol() +
  scale_x_discrete(name="department") +
  ggtitle("Departments by Count x Semester")

```
```{r, echo = FALSE}

#create new data.frame to look at department + course number

raw4 <- raw1 %>% separate(course, into = c("course","course2"),  sep = "\\-", extra = "merge")

course_sum <- as.data.frame(table(raw4$course)) 

#splitting and combining some unique courses with different separators

course_sum <- separate(course_sum, Var1, into = c("a","b", "c"), sep = " ", extra = "merge")

course_sum <- unite(course_sum, course, a, b, sep = " ")

course_sum$c <- NULL

course_sum %>% 
  rename(count = Freq) %>%
  arrange(desc(count)) %>%
  kable(longtable = FALSE)

```

```{r, echo= FALSE}
faculty <- as.data.frame(table(raw1$faculty)) 
faculty %>% arrange(desc(Freq)) %>% rename(Faculty = Var1, n = Freq) %>% kable()

```

